Repository Windermere-Technology/RasPyCam, pull requests merged in 2024-11, with the labels that each got.

#4 Added `%a` schema option to filename generation
  .github/ISSUE_TEMPLATE/bug.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/integration.yml
  README.md
  app/core/model.py
  app/core/process.py
Labels: feature, admin

#2 Fix KeyError caused by missing 'Num' key in Picamera2 camera info
  .github/ISSUE_TEMPLATE/bug.yml
  .github/pull_request_template.md
  app/core/process.py
Labels: bugfix, admin

#8 Updating Integration Trigger
  .github/workflows/integration.yml
Labels: admin, patch

#7 Timelapse feature
  README.md
  app/core/model.py
  app/core/process.py
  app/utilities/capture.py
  app/utilities/motion_detect.py
Labels: feature, minor

#11 Adding `sy` command
  README.md
  app/core/model.py
  app/core/process.py
  app/utilities/capture.py
  app/utilities/motion_detect.py
Labels: feature, minor

#12 Fixing Integration Workflow Rule Break
  .github/workflows/integration.yml
Labels: bugfix, patch
